# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Executables

on:
  workflow_dispatch:
  #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Wine
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y wine64 wine32
    - run: npm install
    - run: npm run clean
    - run: npm run build
    - name: Upload macOS Executable
      uses: actions/upload-artifact@v3
      with:
        name: macOS-executable
        path: build/simulator/osx/
    - name: Upload Windows Executable
      uses: actions/upload-artifact@v3
      with:
        name: Windows-executable
        path: build/simulator/win/
